#version: "3"
services:

  back:
    image: ${BACK_IMAGE_NAME}:${DEPLOYMENT_TAG}
    restart:  on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.back_router.rule=${BACK_ROUTER_RULE}
      - traefik.http.routers.back_router.service=back_service
      - traefik.http.services.back_service.loadbalancer.server.port=80
    environment:
      DATABASE_URL: ${DATABASE_URL}

  mysql:
    image: 'mariadb:10.7.3'
    restart:  on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
  proxy:
    image: traefik:2.4
    container_name: tcm_proxy
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    labels:
      - traefik.enable=false
    ports:
      - "80:80"
    restart:  on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mysql_db:
networks:
  # This could be very usefull to run multiple project on the same machine
  tcm_network:
    name: tcm_network
  default:
    name: tcm_network